Repository MJU-SW-Contest-2024/Nabi-Android, pull requests merged in 2024-08, with the labels that each got.

#27 📖 일기 보기 - 날짜 선택 페이지
  Nabi/data/src/main/java/com/nabi/data/datasource/DiaryRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/DiaryRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/mapper/DiaryMapper.kt
  Nabi/data/src/main/java/com/nabi/data/model/diary/ResponseMonthDiaryDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryRepositoryImpl.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/DiaryInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/MonthDiaryInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DiaryRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/DiaryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/GetMonthlyDiaryUseCase.kt
  Nabi/presentation/build.gradle.kts
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DiaryUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryDayAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryMonthAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthCalendarStateAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/res/drawable/illus_statistics_cat.png
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/fragment_select_date.xml
  Nabi/presentation/src/main/res/layout/fragment_select_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_select_diary_month.xml
  Nabi/presentation/src/main/res/layout/item_select_diary_day.xml
  Nabi/presentation/src/main/res/layout/item_select_diary_month.xml
  Nabi/presentation/src/main/res/values/font_style.xml
  Nabi/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#29 📖 일기 보기 - 일기 검색 페이지
  Nabi/data/src/main/java/com/nabi/data/datasource/DiaryRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/DiaryRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/mapper/DiaryMapper.kt
  Nabi/data/src/main/java/com/nabi/data/model/PageableResponse.kt
  Nabi/data/src/main/java/com/nabi/data/model/diary/SearchDiaryResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/DiaryService.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/PageableInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/DiaryInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/SearchDiary.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DiaryRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/SearchDiaryUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DiaryUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/MainActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_search_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_select_diary.xml
  Nabi/presentation/src/main/res/layout/item_search_diary.xml
  Nabi/presentation/src/main/res/values/font_style.xml
Labels: ✨ Feature

#31 🛠️ 일기 검색 페이징 처리 수정
  Nabi/data/src/main/java/com/nabi/data/model/diary/SearchDiaryResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryRepositoryImpl.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/PageableInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/SearchDiary.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/CustomDecoration.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/utils/DisplayUtils.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/res/layout/item_search_diary.xml
Labels: 🐞 BugFix

#32 📖 일기 보기 - 일기 상세 페이지
  Nabi/data/src/main/java/com/nabi/data/datasource/DiaryRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/DiaryRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/diary/DiaryDetailResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/DiaryService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DiaryRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/GetDiaryDetailUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DiaryUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/OnRvItemClickListener.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/res/drawable/ic_heart.xml
  Nabi/presentation/src/main/res/drawable/ic_heart_filled.xml
  Nabi/presentation/src/main/res/layout/fragment_detail_diary.xml
  Nabi/presentation/src/main/res/values/font_style.xml
Labels: ✨ Feature

#33 🌟 일기 북마크 기능
  Nabi/data/src/main/java/com/nabi/data/datasource/BookmarkRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasource/DiaryRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/BookmarkRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/MessageResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/BookmarkRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/BookmarkService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/BookmarkRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/bookmark/AddBookmarkUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/bookmark/DeleteBookmarkUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/BookmarkUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DataSourceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/RepositoryModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/ServiceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
Labels: ✨ Feature

#35 ⚙️ GitHub Action | Test App Firebase 자동 배포
  Nabi/data/build.gradle.kts
  Nabi/data/src/main/java/com/nabi/data/mapper/DiaryMapper.kt
  Nabi/data/src/main/java/com/nabi/data/mapper/HomeMapper.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DataStoreRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/KakaoAuthService.kt
  Nabi/data/src/main/java/com/nabi/data/utils/LoggerUtils.kt
  Nabi/presentation/build.gradle.kts
  Nabi/presentation/src/main/java/com/nabi/nabi/base/BaseActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/base/NabiApplication.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/fcm/MyFirebaseMessagingService.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/utils/LoggerUtils.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartViewModel.kt
Labels: ✨ Feature

#37 ⚙️ GitHub Action | CI/CD Buld Error Fix
  .github/workflows/app-distribution-ci-cd.yaml
  Nabi/data/src/main/java/com/nabi/data/mapper/HomeMapper.kt
  Nabi/data/src/main/java/com/nabi/data/model/home/RecentFiveDiary.kt
  Nabi/presentation/build.gradle.kts
Labels: 🐞 BugFix

#40 📊 일기 감정 통계 페이지
  Nabi/data/src/main/java/com/nabi/data/datasource/EmotionRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/EmotionRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/emotion/DiaryStatisticsResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/EmotionRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/EmotionService.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/emotion/EmotionStatistics.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/EmotionRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/GetEmotionStatisticsUseCase.kt
  Nabi/gradle/libs.versions.toml
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/CustomChartView.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DataSourceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/EmotionUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/RepositoryModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/ServiceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/res/drawable/ic_down.xml
  Nabi/presentation/src/main/res/layout/fragment_statistics_diary.xml
  Nabi/presentation/src/main/res/values/themes.xml
Labels: ✨ Feature

#42 📊 감정 통계 페이지 | Response 수정
  Nabi/data/src/main/java/com/nabi/data/model/emotion/DiaryStatisticsResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/EmotionRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/EmotionService.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/emotion/EmotionStatistics.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsFragment.kt
Labels: 🐞 BugFix

#43 ✏️ Home 화면 수정
  Nabi/data/src/main/java/com/nabi/data/mapper/HomeMapper.kt
  Nabi/data/src/main/java/com/nabi/data/model/diary/UpdateDiaryRequestDTO.kt
  Nabi/data/src/main/java/com/nabi/data/model/home/RecentFiveDiary.kt
  Nabi/data/src/main/java/com/nabi/data/model/home/ResponseHomeDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryRepositoryImpl.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/home/HomeInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DiaryRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/UpdateDiaryUseCase.kt
  Nabi/presentation/build.gradle.kts
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/base/BaseActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/utils/Constants.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeRvAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeViewModel.kt
  Nabi/presentation/src/main/res/drawable/ic_notify.xml
  Nabi/presentation/src/main/res/layout/fragment_add_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/item_diary.xml
  Nabi/presentation/src/main/res/values/font_style.xml
  Nabi/presentation/src/main/res/values/strings.xml
  Nabi/settings.gradle.kts
Labels: ✨ Feature, 🔨 Refactor

#44 🖋️ 일기 작성 STT 작업, 수정
  Nabi/presentation/src/main/java/com/nabi/nabi/base/BaseActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeRvAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/res/drawable/ic_mic_off.xml
  Nabi/presentation/src/main/res/drawable/ic_mypage.xml
  Nabi/presentation/src/main/res/layout/fragment_add_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/fragment_mypage.xml
Labels: ✨ Feature

#46 📌 Home Bookmark Diary Crash Fix
  Nabi/data/src/main/java/com/nabi/data/datasource/EmotionRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/EmotionRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/repository/EmotionRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/DiaryService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/EmotionRepository.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/base/NabiApplication.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/CustomChartView.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/EmotionUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/fcm/MyFirebaseMessagingService.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeRvAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartViewModel.kt
  Nabi/presentation/src/main/res/layout/fragment_add_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_mypage.xml
Labels: 🐞 BugFix

#48 📖 감정 별 일기 조회 & Custom Number Picker (Only Year and Month)
  Nabi/data/src/main/java/com/nabi/data/datasource/EmotionRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/EmotionRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/emotion/SearchEmotionResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/EmotionRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/EmotionService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/EmotionRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/SearchEmotionUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/EmotionUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/extension/ContextExtension.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/res/drawable/img_anger_gray.png
  Nabi/presentation/src/main/res/drawable/img_anxiety_gray.png
  Nabi/presentation/src/main/res/drawable/img_boredom_gray.png
  Nabi/presentation/src/main/res/drawable/img_happiness_gray.png
  Nabi/presentation/src/main/res/drawable/img_sadness_gray.png
  Nabi/presentation/src/main/res/drawable/shape_non_day_date_picker_bg.xml
  Nabi/presentation/src/main/res/layout/dialog_non_day_date_picker.xml
  Nabi/presentation/src/main/res/layout/fragment_emotion_search.xml
  Nabi/presentation/src/main/res/values/themes.xml
Labels: ✨ Feature

#49 ⚙️ GitHub Action | CI/CD Test PR
  Nabi/presentation/src/main/res/values/themes.xml
Labels: 🐞 BugFix

#54 💬 CustomDialog 구현
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/SearchEmotionUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/base/NabiApplication.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/CustomDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/extension/ContextExtension.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/fcm/MyFirebaseMessagingService.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartViewModel.kt
  Nabi/presentation/src/main/res/drawable/shape_custom_dialog_btn_bg.xml
  Nabi/presentation/src/main/res/drawable/shape_radius_10.xml
  Nabi/presentation/src/main/res/layout/custom_dialog.xml
  Nabi/presentation/src/main/res/values/font_style.xml
Labels: ✨ Feature

#55 💬 대화하기 기능
  Nabi/data/src/main/java/com/nabi/data/datasource/ChatBotRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/ChatBotRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/chat/ChatHistoryResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/model/chat/SendChatRequestDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/ChatBotRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/ChatBotService.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/chat/ChatItem.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/ChatBotRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/chat/EmbeddingDiaryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/chat/GetChatHistoryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/chat/RetryChatResUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/chat/SendChatUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/utils/DateTimeUtils.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/base/NabiApplication.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/ChatBotUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DataSourceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/RepositoryModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/ServiceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatRvAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
  Nabi/presentation/src/main/res/drawable/ic_refresh.xml
  Nabi/presentation/src/main/res/drawable/ic_send.xml
  Nabi/presentation/src/main/res/drawable/shape_chat_my_bg.xml
  Nabi/presentation/src/main/res/drawable/shape_chat_other_bg.xml
  Nabi/presentation/src/main/res/drawable/shape_chat_other_profile.xml
  Nabi/presentation/src/main/res/layout/fragment_chat.xml
  Nabi/presentation/src/main/res/layout/item_chat_date.xml
  Nabi/presentation/src/main/res/layout/item_chat_my.xml
  Nabi/presentation/src/main/res/layout/item_chat_other.xml
  Nabi/presentation/src/main/res/values/font_style.xml
Labels: ✨ Feature

#56 📌 일기 보기 - 날짜 선택 페이지 버그 픽스
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
Labels: 🐞 BugFix

#57 🖋️ 일기에 감정 분석 추가, 삭제
  Nabi/data/src/main/java/com/nabi/data/datasource/DiaryRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasource/EmotionRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/DiaryRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/EmotionRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/diary/DeleteDiaryResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/model/emotion/AddDiaryEmotionResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DataStoreRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/repository/EmotionRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/DiaryService.kt
  Nabi/data/src/main/java/com/nabi/data/service/EmotionService.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/AddDiaryInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/DeleteDiaryMsg.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/emotion/AddDiaryEmotionMsg.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DataStoreRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DiaryRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/EmotionRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/DeleteDiaryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/AddDiaryEmotionUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/GetDiaryEmotionUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/utils/EmotionStateUtils.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/CustomDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/EmotionLoadingDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DiaryUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/EmotionUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
  Nabi/presentation/src/main/res/layout/dialog_add_diary_done.xml
  Nabi/presentation/src/main/res/layout/fragment_add_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_detail_diary.xml
  Nabi/presentation/src/main/res/values/strings.xml
  Nabi/presentation/src/main/res/values/themes.xml
Labels: ✨ Feature, 📝 Modify

#58 🐈‍⬛ 마이페이지 view 작업
  Nabi/presentation/src/main/java/com/nabi/nabi/base/NabiApplication.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/fragment_mypage.xml
  Nabi/presentation/src/main/res/values/font_style.xml
  Nabi/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#59 🖋️ 일기 작성 날짜선택, 임시 저장
  Nabi/data/build.gradle.kts
  Nabi/data/src/main/java/com/nabi/data/repository/DataStoreRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/room/DiaryDAO.kt
  Nabi/data/src/main/java/com/nabi/data/room/DiaryDatabase.kt
  Nabi/data/src/main/java/com/nabi/data/room/DiaryEntity.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DataStoreRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/DeleteDiaryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/AddDiaryEmotionUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/GetDiaryEmotionUseCase.kt
  Nabi/presentation/build.gradle.kts
  Nabi/presentation/src/main/java/com/nabi/nabi/di/LocalModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_add_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_select_diary.xml
  Nabi/presentation/src/main/res/values-night/themes.xml
Labels: ✨ Feature, 🔨 Refactor

#62 🌟 Custom Toast
  Nabi/presentation/src/main/java/com/nabi/nabi/base/BaseActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/base/BaseFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/CustomToast.kt
  Nabi/presentation/src/main/res/drawable/shape_custom_toast_bg.xml
  Nabi/presentation/src/main/res/layout/custom_toast.xml
Labels: ✨ Feature

#66 🖋️ 일기 작성 Calendar 수정
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryDbRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/room/DiaryDAO.kt
  Nabi/data/src/main/java/com/nabi/data/room/DiaryDatabase.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/AddDiaryCallbackItem.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/DiaryDbEntity.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/diary/DiarySelectInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DiaryDbRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/AddTempDiaryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/GetTempDiaryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/UpdateTempDiaryUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/base/BaseActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/custom/EmotionLoadingDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DiaryUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/LocalModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/RepositoryModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/utils/Constants.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryDayAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryMonthAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryMonthCalendarStateAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/SharedDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/res/drawable/img_sign_title.png
  Nabi/presentation/src/main/res/layout/activity_main.xml
  Nabi/presentation/src/main/res/layout/activity_sign.xml
  Nabi/presentation/src/main/res/layout/activity_start.xml
  Nabi/presentation/src/main/res/layout/fragment_add_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_add_diary_month.xml
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/fragment_mypage.xml
  Nabi/presentation/src/main/res/layout/fragment_select_date.xml
  Nabi/presentation/src/main/res/layout/fragment_select_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_sign_nickname.xml
  Nabi/presentation/src/main/res/layout/fragment_sign_provider.xml
  Nabi/presentation/src/main/res/layout/fragment_statistics_diary.xml
  Nabi/presentation/src/main/res/layout/item_month.xml
  Nabi/presentation/src/main/res/values-night/themes.xml
  Nabi/presentation/src/main/res/values/themes.xml
Labels: ✨ Feature, 🧹 Cleanup

#70 📛 닉네임 수정 기능
  Nabi/presentation/src/main/java/com/nabi/nabi/fcm/MyFirebaseMessagingService.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
Labels: 🐞 BugFix, ✨ Feature

#71 🖐️ 최근 로그인 프로바이더 제공 기능
  Nabi/data/src/main/java/com/nabi/data/repository/DataStoreRepositoryImpl.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/DataStoreRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/GetAccessTokenUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/GetAuthProviderUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/GetRecentAuthProviderUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/SaveSignInInfoUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DataStoreUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignNicknameViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartViewModel.kt
  Nabi/presentation/src/main/res/drawable/ic_logo_provider_google.png
  Nabi/presentation/src/main/res/drawable/ic_logo_provider_kakao.png
  Nabi/presentation/src/main/res/drawable/ic_logo_provider_naver.png
  Nabi/presentation/src/main/res/drawable/shape_radius_5.xml
  Nabi/presentation/src/main/res/drawable/shape_radius_5_with_stroke.xml
  Nabi/presentation/src/main/res/layout/fragment_sign_provider.xml
Labels: ✨ Feature

#73 🐞 감정 별 일기 조회 버그 픽스
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchFragment.kt
  Nabi/presentation/src/main/res/values/themes.xml
Labels: 🐞 BugFix

#76 🛠️ SignIn 화면, Home 화면 수정
  Nabi/data/build.gradle.kts
  Nabi/data/src/main/java/com/nabi/data/service/NaverAuthService.kt
  Nabi/gradle/libs.versions.toml
  Nabi/presentation/build.gradle.kts
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/base/NabiApplication.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeRvAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
  Nabi/presentation/src/main/res/drawable/img_main_talk.png
  Nabi/presentation/src/main/res/drawable/img_sign_title.png
  Nabi/presentation/src/main/res/drawable/img_signin_background.png
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/fragment_sign_provider.xml
  Nabi/presentation/src/main/res/values/colors.xml
  Nabi/presentation/src/main/res/values/strings.xml
  Nabi/presentation/src/main/res/values/themes.xml
Labels: ⚙ Setting, ✨ Feature

#78 💬 대화하기 | 기본 프로필 이미지 추가
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatFragment.kt
  Nabi/presentation/src/main/res/drawable/img_default_nabi.png
  Nabi/presentation/src/main/res/layout/item_chat_other.xml
Labels: ✨ Feature

#80 🛠️ 일기 보기 | 일기 선택 캘린더 디자인 수정
  Nabi/presentation/src/main/java/com/nabi/nabi/utils/Constants.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryViewModel.kt
  Nabi/presentation/src/main/res/drawable/img_anger_empty.png
  Nabi/presentation/src/main/res/drawable/img_anxiety_empty.png
  Nabi/presentation/src/main/res/drawable/img_boredom_empty.png
  Nabi/presentation/src/main/res/drawable/img_boredom_empty_gray.png
  Nabi/presentation/src/main/res/drawable/img_happiness_empty.png
  Nabi/presentation/src/main/res/drawable/img_sadness_empty.png
  Nabi/presentation/src/main/res/layout/fragment_select_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_statistics_diary.xml
Labels: 📝 Modify

#82 🚪 카카오 및 서버 회원탈퇴 기능 구현
  Nabi/data/src/main/java/com/nabi/data/datasource/AuthRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/AuthRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/auth/WithdrawResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/AuthRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/AuthService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/AuthRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/auth/WithdrawUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/ClearUserDataUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/AuthUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DataStoreUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/SharedDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartActivity.kt
  Nabi/presentation/src/main/res/layout/activity_sign.xml
  Nabi/presentation/src/main/res/layout/activity_start.xml
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/fragment_mypage.xml
  Nabi/presentation/src/main/res/layout/fragment_sign_provider.xml
  Nabi/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#85 💬 대화하기 | Greeting Msg Refresh Block && Balloon Size Update
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatRvAdapter.kt
Labels: 🐞 BugFix

#87 [feat] Add Emotion Cat Desc Tooltip AutoDismiss
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
Labels: 📝 Modify

#88 📚 외부 일기 불러오기 기능
  Nabi/data/src/main/java/com/nabi/data/datasource/UserRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/UserRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/repository/UserRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/UserService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/UserRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/user/LoadDiaryUseCase.kt
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/di/UserUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageViewModel.kt
  Nabi/presentation/src/main/res/layout/fragment_home.xml
Labels: ✨ Feature

#91 🛠️ 일기 작성 후 뒤로가기 수정
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
Labels: ✨ Feature, 🔨 Refactor

#93 📌 일기 작성, 상세 페이지 fix
  Nabi/presentation/src/main/res/layout/fragment_add_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_detail_diary.xml
  Nabi/presentation/src/main/res/layout/item_month.xml
Labels: 📝 Modify

#94 🔎 감정 분석 재요청 기능
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/res/drawable/img_no_emotion.png
  Nabi/presentation/src/main/res/layout/fragment_detail_diary.xml
Labels: 🐞 BugFix, ✨ Feature

#98 🛠️ 감정 별 일기 조회 | 뒤로가기 수정
  Nabi/data/src/main/java/com/nabi/data/datasource/UserRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/UserRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/repository/DiaryDbRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/repository/UserRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/room/DiaryDAO.kt
  Nabi/data/src/main/java/com/nabi/data/service/NaverAuthService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/UserRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/ClearUserDataUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/GetAccessTokenUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/GetAuthProviderUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/datastore/GetRecentAuthProviderUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/diary/UpdateTempDiaryUseCase.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/user/LoadDiaryUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatRvAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryMonthCalendarStateAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignNicknameViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartViewModel.kt
Labels: 🐞 BugFix

#100 🛠️ 감정분석 화면, 스크롤 뷰 문제 해결
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/NotifyFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_chat.xml
  Nabi/presentation/src/main/res/layout/fragment_detail_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_emotion_search.xml
  Nabi/presentation/src/main/res/layout/fragment_search_diary.xml
  Nabi/presentation/src/main/res/layout/fragment_statistics_diary.xml
  Nabi/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#101 🏷️ 닉네임 설정 | 텍스트 잘림 문제 수정
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_sign_nickname.xml
Labels: 🐞 BugFix

#103 📌 일기작성 날짜선택 viewPager 수정
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiarySelectDateFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_sign_nickname.xml
  Nabi/presentation/src/main/res/layout/item_search_diary.xml
  Nabi/presentation/src/main/res/values/strings.xml
Labels: 🐞 BugFix

#104 🛠️ 뒤로가기 수정
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryMonthFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_select_diary.xml
Labels: 🐞 BugFix, 📝 Modify

#106 🖐️ 앱 이용 가이드 추가
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_mypage.xml
  Nabi/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#108 💡 FCM 히스토리 조회 기능
  Nabi/data/src/main/java/com/nabi/data/datasource/NotificationRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/NotificationRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/notification/NotificationResponseDTO.kt
  Nabi/data/src/main/java/com/nabi/data/model/notification/NotificationResponseDTOItem.kt
  Nabi/data/src/main/java/com/nabi/data/repository/NotificationRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/NotificationService.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/notification/NotificationInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/NotificationRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/notification/GetNotificationUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/NotificationUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/NotifyFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/notification/NotificationAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/notification/NotificationViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/notification/NotifyFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_notify.xml
  Nabi/presentation/src/main/res/layout/item_fcm_notify.xml
  Nabi/presentation/src/main/res/values/font_style.xml
  Nabi/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#109 🖋️ 분석된 감정 사용자 수정 기능
  Nabi/data/src/main/java/com/nabi/data/datasource/EmotionRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/EmotionRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/model/emotion/PatchEmotionResDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/EmotionRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/EmotionService.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/EmotionRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/PatchDiaryEmotionUseCase.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/EmotionUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/UpdateEmotionDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/res/drawable/selector_anger_toggle.xml
  Nabi/presentation/src/main/res/drawable/selector_anxiety_toggle.xml
  Nabi/presentation/src/main/res/drawable/selector_boredom_toggle.xml
  Nabi/presentation/src/main/res/drawable/selector_happiness_toggle.xml
  Nabi/presentation/src/main/res/drawable/selector_sadness_toggle.xml
  Nabi/presentation/src/main/res/layout/dialog_update_emotion.xml
Labels: ✨ Feature

#110 🎨 앱 디자인 시스템
  Nabi/data/src/main/java/com/nabi/data/datasource/EmotionRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/model/notification/NotificationResponseDTO.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/emotion/PatchDiaryEmotionUseCase.kt
  Nabi/presentation/src/main/ic_launcher-playstore.png
  Nabi/presentation/src/main/java/com/nabi/nabi/views/chat/ChatFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/UpdateEmotionDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/search/SearchDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
  Nabi/presentation/src/main/res/drawable/img_nabi_icon.png
  Nabi/presentation/src/main/res/layout/dialog_update_emotion.xml
  Nabi/presentation/src/main/res/layout/item_chat_other.xml
  Nabi/presentation/src/main/res/layout/item_fcm_notify.xml
  Nabi/presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Nabi/presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Nabi/presentation/src/main/res/mipmap-anydpi/ic_launcher.xml
  Nabi/presentation/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  Nabi/presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  Nabi/presentation/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  Nabi/presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Nabi/presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  Nabi/presentation/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  Nabi/presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Nabi/presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Nabi/presentation/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  Nabi/presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Nabi/presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Nabi/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  Nabi/presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Nabi/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Nabi/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  Nabi/presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Nabi/presentation/src/main/res/values/ic_launcher_background.xml
Labels: ✨ Feature, 🧹 Cleanup, 📝 Modify

#111 🐞 로그인 Activity cast 수정
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
Labels: 🐞 BugFix

#114 🛠️ 감정 이름 수정 | 지루함 -> 평온
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/UpdateEmotionDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/emotion/EmotionSearchFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/statistics/DiaryStatisticsFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryDayCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/view/SelectDiaryFragment.kt
  Nabi/presentation/src/main/res/layout/fragment_emotion_search.xml
  Nabi/presentation/src/main/res/values/themes.xml
Labels: 📝 Modify

#115 🧹 Cleanup Project
  Nabi/data/build.gradle.kts
  Nabi/data/src/main/java/com/nabi/data/service/NaverAuthService.kt
  Nabi/domain/src/main/java/com/nabi/domain/extension/EmotionStateUtils.kt
  Nabi/gradle/libs.versions.toml
  Nabi/presentation/build.gradle.kts
  Nabi/presentation/src/main/java/com/nabi/nabi/views/MainActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryCalendarAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/AddDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/add/EmotionLoadingDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/DetailDiaryFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/diary/detail/UpdateEmotionDialog.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/myPage/MyPageFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/splash/StartActivity.kt
  Nabi/presentation/src/main/res/values/font_style.xml
  Nabi/presentation/src/main/res/values/themes.xml
Labels: 🧹 Cleanup
