Repository MJU-SW-Contest-2024/Nabi-Android, pull requests merged in 2024-07, with the labels that each got.

#3 🐱 프로젝트 세팅
  Nabi/build.gradle.kts
  Nabi/data/build.gradle.kts
  Nabi/data/src/main/java/com/nabi/data/LoggerUtils.kt
  Nabi/gradle/libs.versions.toml
  Nabi/presentation/build.gradle.kts
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/MainActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/base/NabiApplication.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/AppModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/utils/PrettyJsonLogger.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/utils/UiState.kt
Labels: ⚙ Setting

#7 ✏️ 메인 페이지 작업
  Nabi/data/src/main/java/com/nabi/data/datasource/HomeRemoteDataSource.kt
  Nabi/data/src/main/java/com/nabi/data/datasourceImpl/HomeRemoteDataSourceImpl.kt
  Nabi/data/src/main/java/com/nabi/data/mapper/HomeMapper.kt
  Nabi/data/src/main/java/com/nabi/data/model/home/RecentFiveDiary.kt
  Nabi/data/src/main/java/com/nabi/data/model/home/ResponseHomeDTO.kt
  Nabi/data/src/main/java/com/nabi/data/repository/HomeRepositoryImpl.kt
  Nabi/data/src/main/java/com/nabi/data/service/HomeService.kt
  Nabi/domain/src/main/java/com/nabi/domain/model/home/HomeInfo.kt
  Nabi/domain/src/main/java/com/nabi/domain/repository/HomeRepository.kt
  Nabi/domain/src/main/java/com/nabi/domain/usecase/home/HomeUseCase.kt
  Nabi/presentation/src/androidTest/java/com/nabi/nabi/ExampleInstrumentedTest.kt
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/MainActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/DataSourceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/HomeUseCaseModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/RepositoryModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/di/ServiceModule.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/MainActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/MainRvAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/MainViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInProviderFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInViewModel.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignNicknameViewModel.kt
  Nabi/presentation/src/main/res/drawable/ic_graph.xml
  Nabi/presentation/src/main/res/drawable/ic_left.xml
  Nabi/presentation/src/main/res/drawable/ic_right.xml
  Nabi/presentation/src/main/res/drawable/ic_search.xml
  Nabi/presentation/src/main/res/drawable/shape_circle.xml
  Nabi/presentation/src/main/res/drawable/shape_radius_20.xml
  Nabi/presentation/src/main/res/layout/activity_main.xml
  Nabi/presentation/src/main/res/layout/fragment_sign_nickname.xml
  Nabi/presentation/src/main/res/layout/fragment_sign_provider.xml
  Nabi/presentation/src/main/res/layout/item_diary.xml
  Nabi/presentation/src/main/res/values/colors.xml
  Nabi/presentation/src/main/res/values/strings.xml
  Nabi/presentation/src/main/res/values/themes.xml
  Nabi/presentation/src/test/java/com/nabi/nabi/ExampleUnitTest.kt
Labels: ✨ Feature, 🧹 Cleanup

#9 🖋️ 일기 작성 - 날짜 선택 페이지
  Nabi/presentation/src/main/AndroidManifest.xml
  Nabi/presentation/src/main/java/com/nabi/nabi/views/MainActivity.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/addDiary/DayAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/addDiary/MonthAdapter.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/addDiary/SelectDateFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/home/HomeFragment.kt
  Nabi/presentation/src/main/java/com/nabi/nabi/views/sign/SignInNicknameFragment.kt
  Nabi/presentation/src/main/res/drawable/ic_back.xml
  Nabi/presentation/src/main/res/drawable/shape_radius_top_20.xml
  Nabi/presentation/src/main/res/layout/activity_main.xml
  Nabi/presentation/src/main/res/layout/fragment_home.xml
  Nabi/presentation/src/main/res/layout/fragment_select_date.xml
  Nabi/presentation/src/main/res/layout/item_day.xml
  Nabi/presentation/src/main/res/layout/item_diary.xml
  Nabi/presentation/src/main/res/layout/item_month.xml
  Nabi/presentation/src/main/res/values/font_style.xml
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor

#10 🎨 디자인 시스템
  Nabi/presentation/src/main/res/drawable/ic_arrow.xml
  Nabi/presentation/src/main/res/drawable/ic_cancel.xml
  Nabi/presentation/src/main/res/drawable/img_anger.png
  Nabi/presentation/src/main/res/drawable/img_anxiety.png
  Nabi/presentation/src/main/res/drawable/img_boredom.png
  Nabi/presentation/src/main/res/drawable/img_happiness.png
  Nabi/presentation/src/main/res/drawable/img_sadness.png
  Nabi/presentation/src/main/res/font/pretendard_bold.otf
  Nabi/presentation/src/main/res/font/pretendard_regular.otf
  Nabi/presentation/src/main/res/font/pretendard_semi_bold.otf
  Nabi/presentation/src/main/res/layout/preview_design_system.xml
  Nabi/presentation/src/main/res/values/font_style.xml
Labels: ⚙ Setting
